apiVersion: v1
kind: Template
labels:
  template: thoth-build-analysers-api-buildconfig
  thoth: 0.1.0
metadata:
  name: thoth-build-analysers-api-buildconfig
  annotations:
    description: This is Thoth Build Analysers API BuildConfig, this template is meant to be used by Jenkins, but could also be used by humans...
    openshift.io/display-name: Thoth Build Analysers API BuildConfig
    version: 0.1.0
    tags: poc,thoth,thoth-build-analysers-api,ai-stacks
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: This is Thoth Build Analysers API BuildConfig, this template is meant to be used by Jenkins, but could also be used by humans...
    template.openshift.io/provider-display-name: Red Hat, Inc.

objects:
#
# Image streams
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: thoth-core
    name: build-analysers-api
  spec:
    name: ${IMAGE_STREAM_TAG}

#
# Build configs
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: build-analysers-api
    labels:
      app: thoth-core
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: "build-analysers-api:${IMAGE_STREAM_TAG}"
    source:
      type: Git
      git:
        uri: ${GITHUB_URL}
        ref: ${GITHUB_REF}
    strategy:
      type: Source
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: python-36-centos7:latest
    triggers:
    - type: ImageChange
      imageChange: {}

parameters:
- description: Git repository for Thoth's Build Analysers API
  displayName: Thoth build-analysers-api git repository
  required: true
  name: GITHUB_URL
  value: 'https://github.com/thoth-station/build-analysers-api'

- description: Git repository for Thoth's Build Analysers API
  displayName: Thoth build-analysers-api git reference
  required: true
  name: GITHUB_REF
  value: 'master'

- description: Tag of the output ImageStream the resulting container image should go to
  displayName: ImageStream Tag
  required: true
  name: IMAGE_STREAM_TAG
  value: 'latest'